### PR TITLE
First proposal for a ReadMe file

### PR DESCRIPTION
**Pull request by jfoucry**
This is a first proposal for a Readme.md file for this repository

### CODE REVIEW

**Comment by jfoucry** [comment]
See issue #1

**Comment by jfoucry** [comment]
- My memory was of about markdown syntax :-)
- Is it the right Readme for calling for other than translation?
- Flags are not languages… But you're right, we start with flags, let's continue with.

I will reread to avoid typos.

Fix #1

**Comment by simpnu** [comment]
>     * My memory was of about markdown syntax :-)
No worries, feel free to check here to see how it looks: https://github.com/Exodus-Privacy/website/tree/readme :)

>     * Is it the right Readme for calling for other than translation?
What I mean is that if someone wants to improve something on the website (better organize the contribute or the events page for instance), why not :)

>     * Flags are not languages… But you're right, we start with flags, let's continue with.
Hmm, I agree with you. If you have a better idea to show the 2 distinct languages, feel free :). 

>     * I will reread to avoid typos.
I can take a last look after that and directly correct the ones I see if you want.

**Comment by simpnu** [comment]
Made #9 to integrate some changes into this README

**Pull request merged**
