### PR TITLE
feat (header): Highlight page name on the navigation bar!

### LINKED ISSUE #197: Highlight page name on the navigation bar
Similar to what we have in the exodus platform, it would be great if the active page would be highlighted on the navigation bar (see screenshot below).

image

### PR DESCRIPTION
**Pull request by ArnavK-09**
image

## Fixes #197

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@pnu-s 👋

**Review by codeurimpulsif — CHANGES_REQUESTED** [review]
Thanks for your PR, but please don't put CSS style in HTML files, put it in CSS files (`themes/hugo-bootstrap/static/assets/css/custom.css` seems to be a good place for this).

**Comment by ArnavK-09** [comment]
@codeurimpulsif 👋

**Review by codeurimpulsif — APPROVED** [review]
Seems ok for me, thanks!

**Comment by ArnavK-09** [comment]
> Seems ok for me, thanks!

Merge?

**Pull request merged**
